### ISSUE TITLE
USB battery charger

### ISSUE THREAD

**Issue by dmazzella** [kriswiner/Rodan#2]
Hi Kris,
are you going to integrate a USB battery charger in a new version?

Thank you,
D.

**Comment by kriswiner** [comment]
Well, the idea was to charge the battery using the solar cell but I am not
too happy with this, so I might just drop the solar charger and in this
case I would add an SYBC08 battery charger from USB. Rodan is supposed to
be ultra-low-power anyway so even a small 300 mAH LiPo should last for
months. I was hoping to have something I could permanently mount outside
and never have to wrry about charging. But I suppose having to charge once
every three or six months isn't too bad.

**Comment by dmazzella** [comment]
Ok, thanks for sharing.

I'm waiting for updates and a link to buy some pre-assembled Rodan

**Comment by kriswiner** [comment]
The design is open source so you can modify and produce these as you like.
I don;t have plans to produce them in any quantity or for sale at Tindie,
for example. If your demand quantity was high enough, I might have a
production run in China made. How many would you want?
